README.md
doc/assets/postman/XS2A_N26_Sandbox.postman_collection.json
doc/assets/postman/XS2A_N26_Sandbox.postman_environment.json

Add sandbox postman collections

OB-1691-documentation-update

---

doc/fallback-aisp.md
doc/fallback-pisp.md

OB-1349-documentation-update

---

README.md
doc/assets/openapi/additional_api_spec.md

OB-2059 Added bankTransactionCode info

---

doc/fallback-aisp.md

[OB-1686] Update fallback-aisp.md
[OB-1686]: https://number26-jira.atlassian.net/browse/OB-1686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OB-1686-documentation-update

---

doc/fallback-pisp.md

Update Standing Orders documentation

OB-2186-documentation-update

---

doc/fallback-pisp.md

OB-2066-documentation-update

---

doc/dedicated-pisp.md

Add note that debtorAccount is optional

OB-2275-documentation-update

---

doc/fallback-pisp.md

OB-2338-documentation-update

---

doc/fallback-pisp.md

Enable Standing Orders Fallback

OB-2379-documentation-update

---

doc/assets/postman/XS2A_N26_Sandbox.postman_collection.json
doc/dedicated-pisp.md

OB-2399-documentation-update

---

README.md
doc/fallback-pisp.md

OB-2415-documentation-update

---

doc/assets/postman/XS2A_N26_Sandbox.postman_collection.json

OB-2540-documentation-update

---

doc/dedicated-aisp.md
doc/fallback-pisp.md

Updating txn examples to include linkID

OB-2628-documentation-update

---

doc/fallback-pisp.md

Include T&C redirect in documentation

OB-2626-documentation-update

---

doc/sandbox.md

Authenticate multiple users on Sandbox

OB-2883-documentation-update

---

README.md
doc/dedicated-aisp.md

Pagination when getting transaction list

OB-2914-documentation-update

---

doc/dedicated-aisp.md

Update the docs to reflect pagination list

OB-2819-documentation-update

---

README.md
doc/fallback-aisp.md
doc/fallback-pisp.md

New payment status endpoint on the Fallback Interface

OB-3086-documentation-update

---

README.md
doc/dedicated-pisp.md
doc/fallback-pisp.md
doc/sandbox.md

OB-3218-documentation-update

---

README.md
doc/dedicated-aisp.md
doc/dedicated-cbpii.md
doc/dedicated-pisp.md
doc/fallback-aisp.md
doc/fallback-pisp.md

We updated these sections:
Key announcements
General FAQs
Dedicated AISP doc
Dedicated PISP doc
Dedicated CBPII doc
Fallback AISP doc
Fallback PISP doc

[PS-7519] Update aisp, cbpii, pisp docs with rate limiting updates
